services:
  pg:
    build:
      context: .
      dockerfile: pg.dockerfile
    container_name: cervo_pg
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cervo

  grafana:
    image: grafana/otel-lgtm
    container_name: cervo-grafana
    ports:
      - 12345:3000
      - 4317:4317
      - 4318:4318

  redis:
    image: redis:alpine
    container_name: cervo_redis
