name: E2E Tests

on: push

jobs:
  run-ci:
    name: Run E2E Tests
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install
        run: bun install

      - name: Pretest
        run: bun run pretest

      - name: Test
        run: bun run test
